### ISSUE TITLE
Send bio, url, and status

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/digitalungdom-api#1]
Hi, I would like you to also send the bio, url and status of a profile.

Thanks!

https://github.com/digitalungdom-se/digitalungdom-api/blob/5725e49f83298b65f9c9d19098cd7c95b3d6ee3c/src/api/controllers/user.ts#L83-L94

**Comment by kelszo** [comment]
Doesn't it? Have you set it before requesting?

This image is from the tests:
![image](https://user-images.githubusercontent.com/41587072/99182512-41730280-272d-11eb-8a31-dc4fb1ca4835.png)

**Comment by Nautman** [comment]
I'd also like you to send gender and birthdate.

I haven't set it before. That probably fixes it!

**Comment by kelszo** [comment]
Should we really send that for public profiles?

**Comment by Nautman** [comment]
You're right. I need it for `/user/@me` though.

**Comment by kelszo** [comment]
Aha, yes

**Comment by Nautman** [comment]
Let me know when you have fixed these issues and when they have been committed. Then I will commit my fixing changes to front-end.
