### ISSUE TITLE
Receive notifications in most recent order for get request

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/digitalungdom-api#15]
Currently, the notification system receives the oldest notifications first. This is rather backwards, as you would normally like to see the new notifications first, and then scroll down to see the older ones. While I could see the logic in having old notifications first, it would only be logical if users were to delete the already read notifications.

**Comment by kelszo** [comment]
Done, note with the latest patch the `at` field has been removed since it is redundant (date is included in the mongoID/objectID)

**Comment by Nautman** [comment]
Great, thanks for letting me know of breaking changes!
