### ISSUE TITLE
It's possible to change your username to the value null

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/digitalungdom-api#5]
It's done with `put("/user@me")`.

**Comment by kelszo** [comment]
Thank you! This is a major fault on my side, I miss read the documentation thinking `nullable: false` meant that the field could not be nullable. Fixed in this repoo and all my other xd.

**Comment by Nautman** [comment]
It's still possible to do so. This is my `put("/user/@me")` request.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/28629647/99185236-6ae95980-2740-11eb-9934-13b7a79d55e3.png">
