### ISSUE TITLE
A link should be sent with the login code email

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/digitalungdom-api#8]
Hi,

I was wondering if there was a link sent with the login code email?
If so, what is the structure of the link, i.e.

`digitalungdom.se/verify/:bearer`

where `bearer` is `email + ":" + loginCode` in base64?

**Comment by Zigolox** [comment]
I think there should be sent with the login code email and that it should be stated that the link is preferred to the text since it is more secure.

**Comment by kelszo** [comment]
Atm no link is sent

**Comment by Zigolox** [comment]
We should send a link with a random code. I'm re-purposing this issue for also sending a link.

**Comment by kelszo** [comment]
I do not see the point so this will be low priority.

**Comment by Nautman** [comment]
I think it's a very useful feature. Is it possible for you to commit the HTML templates for the SendGrid emails? Perhaps me or @Zigolox can help!

**Comment by Nautman** [comment]
I don't think this is necessary for MVP.

**Comment by kelszo** [comment]
Fixed as of commit 6e4072a
